#!/bin/sh

start() {
	mount -t configfs configfs /sys/kernel/config || return 1
	truncate -s 4M /tmp/img
	echo "Starting Lioness..."
	start-stop-daemon -S -q -p /var/run/lioness.pid \
		--exec /usr/bin/lioness \
		-- /tmp/img /sys/kernel/config /proc/cmdline
}

stop() {
	printf "Stopping Lioness"
	start-stop-daemon -K -q -p /var/run/lioness.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
