#!/bin/sh

start() {
	# TODO: check for firstboot
	/app/setup.sh
}

case "$1" in
        start)
                start "Running";;
        restart|reload)
                :;;
        stop)
                :;;
        *)
                echo "Usage: $0 {start|stop|restart|reload}"
                exit 1
esac
